"""Default seed content for Juan Maulana / Koda's Field Log showcase.
All writing below is original placeholder content."""

DEFAULT_NOTEBOOKS = [
    {
        "slug": "about",
        "label": "About me",
        "variant": "orange",
        "subtitle": ["Graph Paper Memo Book", "Expedition Orange / Written in Indonesia"],
        "entries": [
            {"type": "about", "title": "Hello, I'm Juan.", "meta": "Writer of quiet things",
             "body": "I write novels, short stories, poems and journals from a small desk that faces a wall, because windows are a distraction and walls are excellent listeners. My work is about ordinary people carrying extraordinary weather inside them \u2014 monsoons, ashfall, the occasional impossible train."},
            {"type": "about", "title": "Who is Koda?", "meta": "The counterpart",
             "body": "Koda is the counterpart of Juan \u2014 he is the one who writes. Juan buys the coffee, answers the emails, misses the deadlines. Koda shows up at 3 AM, borrows Juan's hands, and leaves pages behind like footprints. Neither of us fully trusts the other. The work is better for it."},
            {"type": "about", "title": "What I write", "meta": "Four notebooks, one desk",
             "body": "Novels \u2014 long weather systems that take years to pass. Short stories \u2014 single storms, gone by morning. Poetry \u2014 the lightning itself. Journals \u2014 the smell of the ground after. Everything here is a field log of the same country, mapped in different scales."},
            {"type": "about", "title": "Say hello", "meta": "The desk is always open",
             "body": "For commissions, collaborations, or to argue about semicolons:\n\nhello@juanmaulana.id\n@kodawrites\nkoda.substack.com"},
        ],
    },
    {
        "slug": "writings",
        "label": "Writings",
        "variant": "paper",
        "subtitle": ["Graph Paper Memo Book", "Custom / Written in Indonesia"],
        "entries": [
            {"type": "piece", "category": "Novel", "title": "The Cartographer of Silence",
             "date": "2025 \u2014 in progress", "meta": "A novel in chapters",
             "body": "Aru draws maps of places that make no sound \u2014 and the old radio station on the hill is the quietest place of all.",
             "chapters": [
                 {"title": "I. The Commission",
                  "body": "Aru drew maps of places that made no sound. Not quiet places \u2014 silent ones, where even memory kept its shoes off. The commission arrived on a Tuesday: chart the old radio station on the hill, the one that stopped broadcasting the night his mother left. He packed a compass, three pencils, and the kind of courage that only looks like courage from far away.\n\nThe gate was open. The gate was always open. That was the first thing he wrote down."},
                 {"title": "II. The Antenna",
                  "body": "The antenna still pointed at the sky the way old men point at photographs \u2014 certain that something is there, unable to say its name. Aru measured its shadow at noon and again at four, and the difference between the two measurements was exactly the length of the apology his father never gave.\n\nHe noted this down in the margin, under 'anomalies'."},
                 {"title": "III. Static",
                  "body": "On the third night, the receiver crackled. Not with a voice \u2014 he was careful, later, never to claim a voice \u2014 but with the particular static of a room where someone has just finished speaking. Aru sat very still. The map under his hands was blank in the middle, the way all his maps were blank in the middle.\n\nHe finally understood what the blankness was for."},
             ]},
            {"type": "piece", "category": "Novel", "title": "Rain Over Batavia",
             "date": "2024", "meta": "A novel in chapters",
             "body": "It has been raining for nine years, and Saskia is finally going to open the box her grandfather left behind.",
             "chapters": [
                 {"title": "Prologue \u2014 The Canals",
                  "body": "The city learned to breathe underwater long before the floods came. Every November the canals rehearsed their old Dutch names, and every December they forgot them again. Saskia counted umbrellas from the third-floor window of the archive \u2014 forty-one, forty-two \u2014 and decided that today, finally, she would open the box her grandfather had labeled DO NOT OPEN UNTIL THE RAIN STOPS.\n\nIt had been raining for nine years."},
                 {"title": "1. The Archive",
                  "body": "The archive smelled of wet paper and patience. Saskia's job was to catalogue the letters of people long dead, which she liked, because the dead never asked for their letters back. The box sat on her desk all morning, sweating quietly in the humidity, and by noon she had invented eleven reasons not to open it and one very good reason to do it anyway.\n\nThe good reason won. It usually does, in books like this."},
             ]},
            {"type": "piece", "category": "Short Story", "title": "The Last Train to Lembang",
             "date": "March 2025", "meta": "Complete \u2014 3,200 words",
             "body": "There has never been a train to Lembang. Everyone in the station knew this, which is why nobody questioned the ticket in Dimas's hand, printed on paper that smelled like his father's jacket. Platform 9 did not exist either, but grief is an excellent engineer. The conductor checked his ticket, nodded, and said the thing conductors always say to the recently bereaved: mind the gap."},
            {"type": "piece", "category": "Short Story", "title": "Paper Boats",
             "date": "January 2025", "meta": "Complete \u2014 1,800 words",
             "body": "We raced paper boats in the gutter every monsoon, my brother and I, and every year his boat won because he folded his out of pages from books he had already finished, and I folded mine out of homework I refused to do. Paper remembers what was written on it, he said. Words about journeys travel farther.\n\nThe year he got sick, I folded a boat from a blank page. It refused to float. I have been writing on every page since."},
            {"type": "piece", "category": "Poetry", "title": "Ashfall",
             "date": "May 2025", "meta": "Poem",
             "body": "The mountain cleared its throat\nand the whole town went grey and holy \u2014\nlaundry lines like prayer flags,\nmotorbikes wearing veils of dust.\n\nMy grandmother swept the porch twice,\nnot because it helped\nbut because sweeping\nis a language the sky understands:\n\nwe are still here,\nwe are still here,\nsend rain."},
            {"type": "piece", "category": "Poetry", "title": "Monsoon Arithmetic",
             "date": "February 2025", "meta": "Poem",
             "body": "Count the seconds between lightning\nand the answer:\nthat is how far away the sky is\nfrom keeping its promises.\n\nCount the buckets in the hallway:\nthat is how many songs\nthe roof knows by heart.\n\nCount the times you said\nI'll leave when the rain stops \u2014\nthat is the number\nof reasons you stayed."},
            {"type": "piece", "category": "Journal", "title": "Notes from a Tuesday",
             "date": "June 2025", "meta": "Journal entry",
             "body": "Woke up at six to write and instead watched the neighbor's cat conduct an orchestra of pigeons. Made coffee. Made a second coffee to apologize to the first one. The novel is stuck at the part where something has to happen, which is unfortunate, because I specialize in the parts where nothing does.\n\nWrote 400 words anyway. Deleted 300. The remaining 100 might be the best thing I've done all month. Tuesday: won on points."},
            {"type": "piece", "category": "Journal", "title": "On Writing at 3 AM",
             "date": "April 2025", "meta": "Journal entry",
             "body": "Everyone romanticizes writing at 3 AM, and everyone is correct. At 3 AM the inner critic is asleep and the sentences come out wearing pajamas, honest and unbrushed. Koda does his best work at this hour \u2014 I just hold the pen.\n\nIn the morning I read what we wrote and I don't recognize half of it, which is exactly the point. You cannot surprise a reader if you have never once surprised yourself."},
        ],
    },
    {
        "slug": "kind-words",
        "label": "Kind words",
        "variant": "blue",
        "subtitle": ["Graph Paper Memo Book", "Custom / Written in Indonesia"],
        "entries": [
            {"type": "kind", "title": "Sarah Wijaya", "meta": "Editor, Arus Literary",
             "body": "Juan writes the way rain sounds on a tin roof \u2014 you don't realize you've been listening for an hour until it stops."},
            {"type": "kind", "title": "Daniel Chen", "meta": "Reader & book blogger",
             "body": "Paper Boats broke me in eighteen hundred words. I have read novels that tried for four hundred pages and got nowhere near."},
            {"type": "kind", "title": "Ayu Prameswari", "meta": "Writing workshop mentor",
             "body": "His journals are proof that an ordinary Tuesday, honestly observed, beats an extraordinary plot lazily told."},
            {"type": "kind", "title": "Marcus Tan", "meta": "Fellow writer",
             "body": "There are two writers in there \u2014 Juan and Koda \u2014 and I genuinely cannot tell which one keeps making me cry on public transport."},
        ],
    },
]
